<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="GBAGUIDI_Ursus">

<title>Analyse de la volatilité de l’indice CAC40</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Garch_CAC40_files/libs/clipboard/clipboard.min.js"></script>
<script src="Garch_CAC40_files/libs/quarto-html/quarto.js"></script>
<script src="Garch_CAC40_files/libs/quarto-html/popper.min.js"></script>
<script src="Garch_CAC40_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Garch_CAC40_files/libs/quarto-html/anchor.min.js"></script>
<link href="Garch_CAC40_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Garch_CAC40_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Garch_CAC40_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Garch_CAC40_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Garch_CAC40_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analyse de la volatilité de l’indice CAC40</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>GBAGUIDI_Ursus </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="modélisation-garch-analyse-de-la-volatilité-de-lindice-cac40" class="level1">
<h1>Modélisation GARCH : Analyse de la volatilité de l’indice CAC40</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>L’indice CAC40 représente la performance des 40 plus grandes capitalisations cotées à la Bourse de Paris. Il constitue un indicateur majeur de l’économie française et de la zone euro, largement suivi par les investisseurs institutionnels et particuliers. La dynamique du CAC40 est influencée par les conditions macroéconomiques (politique monétaire de la BCE, inflation, croissance), les résultats financiers des entreprises, ainsi que par les événements géopolitiques et les mouvements globaux des marchés boursiers.</p>
<p>L’étude de la volatilité des rendements de l’indice est essentielle pour comprendre le risque de marché et pour la prise de décisions financières éclairées.</p>
</section>
<section id="problématique" class="level2">
<h2 class="anchored" data-anchor-id="problématique">2. Problématique</h2>
<p>La volatilité du CAC40 varie dans le temps et peut présenter des périodes de forte instabilité. Cette instabilité complique la gestion du risque, la tarification des produits dérivés et l’élaboration de stratégies de couverture ou de trading. Il est donc crucial de disposer d’un modèle capable de <strong>capturer les variations conditionnelles de la variance</strong> des rendements et de prévoir la volatilité future.</p>
</section>
<section id="objectifs" class="level2">
<h2 class="anchored" data-anchor-id="objectifs">3. Objectifs</h2>
<p>L’objectif de cette étude est d’analyser et de modéliser la volatilité de l’indice CAC40 à l’aide des modèles GARCH (Generalized Autoregressive Conditional Heteroskedasticity). Cette modélisation permettra de :</p>
<ul>
<li><p>Estimer la variance conditionnelle des rendements sur différentes périodes.</p></li>
<li><p>Améliorer la gestion du risque de marché.</p></li>
</ul>
</section>
<section id="méthodologie" class="level2">
<h2 class="anchored" data-anchor-id="méthodologie">4. Méthodologie</h2>
<p>L’analyse se déroulera en plusieurs étapes :</p>
<ol type="1">
<li>Récupération des cours historiques de l’indice (prix de clôture).</li>
<li>Calcul des rendements logarithmiques ou simples.</li>
<li>Vérification de la stationnarité des séries temporelles.</li>
<li>Estimation d’un modèle GARCH adapté aux rendements.</li>
<li>Validation du modèle via des tests d’autocorrélation des résidus, tests ARCH-LM et QQ-plots.</li>
<li>Prévisions de la volatilité future et évaluation des métriques de risque.</li>
</ol>
<p>Ce cadre permettra de mieux comprendre et anticiper la dynamique de volatilité du CAC40.</p>
<section id="importation-des-packages" class="level3">
<h3 class="anchored" data-anchor-id="importation-des-packages">Importation des packages</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Importation des bibliothèques</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Récupération et manipulation des données financières</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quantmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'quantmod' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Le chargement a nécessité le package : xts</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'xts' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Le chargement a nécessité le package : zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'zoo' a été compilé avec la version R 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attachement du package : 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Les objets suivants sont masqués depuis 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Le chargement a nécessité le package : TTR</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'TTR' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'tidyverse' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'ggplot2' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'tibble' a été compilé avec la version R 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'tidyr' a été compilé avec la version R 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'readr' a été compilé avec la version R 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'purrr' a été compilé avec la version R 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'dplyr' a été compilé avec la version R 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'stringr' a été compilé avec la version R 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'forcats' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'lubridate' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.1
✔ ggplot2   4.0.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::first()  masks xts::first()
✖ dplyr::lag()    masks stats::lag()
✖ dplyr::last()   masks xts::last()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tests statistiques (stationnarité, autocorrélation...)</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tseries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'tseries' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'lmtest' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modélisation GARCH</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rugarch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'rugarch' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Le chargement a nécessité le package : parallel

Attachement du package : 'rugarch'

L'objet suivant est masqué depuis 'package:purrr':

    reduce</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisation</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="importation-du-jeu-de-données-et-calcul-des-rendements" class="level2">
<h2 class="anchored" data-anchor-id="importation-du-jeu-de-données-et-calcul-des-rendements">Importation du jeu de données et calcul des rendements</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quantmod)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Télécharger les données</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">getSymbols</span>(<span class="st">"^FCHI"</span>, <span class="at">from =</span> <span class="st">"2020-01-01"</span>, <span class="at">to =</span> <span class="st">"2024-12-31"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "FCHI"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Extraire les prix de clôture</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>cac40_close <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(FCHI[, <span class="st">"FCHI.Close"</span>])</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Calcul des rendements log</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>cac40_returns <span class="ot">&lt;-</span> <span class="fu">dailyReturn</span>(cac40_close, <span class="at">type =</span> <span class="st">"log"</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cac40_returns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           daily.returns
2020-01-02  0.0000000000
2020-01-03  0.0004402170
2020-01-06 -0.0050706604
2020-01-07 -0.0002061787
2020-01-08  0.0030971311
2020-01-09  0.0019132415</code></pre>
</div>
</div>
<p>Le jeu de donnée a été bien importé</p>
</section>
<section id="analyse-descriptive" class="level2">
<h2 class="anchored" data-anchor-id="analyse-descriptive">Analyse descriptive</h2>
<section id="visualisation-des-donnees" class="level3">
<h3 class="anchored" data-anchor-id="visualisation-des-donnees">Visualisation des donnees</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Data frame pour ggplot</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>prices_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Date =</span> <span class="fu">index</span>(cac40_close),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Close =</span> <span class="fu">as.numeric</span>(cac40_close)   <span class="co"># convertir en numeric</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>returns_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Date =</span> <span class="fu">index</span>(cac40_returns),</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Return =</span> <span class="fu">as.numeric</span>(cac40_returns)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisation des prix</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(prices_df, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Close)) <span class="sc">+</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Prix de clôture du CAC40"</span>, <span class="at">x =</span> <span class="st">"Date"</span>, <span class="at">y =</span> <span class="st">"Prix (points)"</span>) <span class="sc">+</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><img src="http://127.0.0.1:8799/chunk_output/D97F65661e9ea445/C790293C/cfwj27cnd6nca/000014.png" class="img-fluid"></p>
</section>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
</section>
</section>
<section id="analyse-du-prix-de-clôture-du-cac40-20102025" class="level1">
<h1>Analyse du prix de clôture du CAC40 (2010–2025)</h1>
<section id="description-visuelle" class="level2">
<h2 class="anchored" data-anchor-id="description-visuelle">1. Description visuelle</h2>
<p>Le graphique montre l’évolution du <strong>prix de clôture du CAC40</strong> sur une période de 5 ans, de 2020 à 2025.</p>
<ul>
<li>Le niveau du CAC40 est passé d’environ <strong>6000 points en 2020</strong> à plus de <strong>8 000 points en 2025</strong>.</li>
<li>La tendance générale est <strong>clairement haussière</strong></li>
</ul>
<hr>
</section>
<section id="observations-clés" class="level2">
<h2 class="anchored" data-anchor-id="observations-clés">2. Observations clés</h2>
<section id="tendance-long-terme" class="level3">
<h3 class="anchored" data-anchor-id="tendance-long-terme">Tendance long terme</h3>
<ul>
<li>Croissance globale de <strong>+130 %</strong> sur la période reflète la performance boursière française sur 5 ans.</li>
</ul>
</section>
<section id="volatilité" class="level3">
<h3 class="anchored" data-anchor-id="volatilité">Volatilité</h3>
<ul>
<li>Le marché semble <strong>nerveux</strong> ces dernières années, avec des pics et creux plus fréquents.</li>
</ul>
<hr>
</section>
</section>
<section id="interprétation-économique" class="level2">
<h2 class="anchored" data-anchor-id="interprétation-économique">3. Interprétation économique</h2>
<ul>
<li>Le CAC40 suit les <strong>grandes tendances macroéconomiques</strong> : croissance, crises, politiques monétaires, événements géopolitiques.</li>
<li>La forte hausse entre 2020 et 2022 s’explique par :
<ul>
<li>Les <strong>stimulus budgétaires et monétaires massifs</strong>.</li>
<li>La <strong>reprise post-pandémique</strong>.</li>
<li>L’appréciation des valeurs technologiques et cycliques.</li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p>Ce graphique illustre bien que les indices boursiers ne suivent pas un chemin lisse ils réagissent aux <strong>chocs économiques et psychologiques</strong> des investisseurs.</p>
</blockquote>
<hr>
</section>
<section id="implications-pour-la-modélisation" class="level2">
<h2 class="anchored" data-anchor-id="implications-pour-la-modélisation">4. Implications pour la modélisation</h2>
<ul>
<li>Cette série est <strong>non stationnaire</strong> (tendance claire + racine unitaire probable).</li>
<li>Pour toute analyse statistique ou prévisionnelle, il faut :
<ol type="1">
<li><strong>Passer aux rendements logarithmiques</strong> (différences premières du log).</li>
<li>Vérifier la <strong>stationnarité</strong> (test ADF).</li>
<li>Analyser la <strong>volatilité conditionnelle</strong> (carré des rendements, test ARCH-LM).</li>
</ol></li>
</ul>
<p>Prochaine étape : calculer les <strong>rendements</strong>, puis effectuer les <strong>tests ADF, ARCH-LM</strong> et tracer les <strong>ACF/PACF</strong> pour valider la spécification du modèle.</p>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2"></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisation des rendements</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(returns_df, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Return)) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Rendements logarithmiques CAC40"</span>, <span class="at">x =</span> <span class="st">"Date"</span>, <span class="at">y =</span> <span class="st">"Rendement"</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="graphique-2-rendements-logarithmiques" class="level2">
<h2 class="anchored" data-anchor-id="graphique-2-rendements-logarithmiques">Graphique 2 : Rendements logarithmiques</h2>
<p>Ce graphique représente les <strong>rendements logarithmiques quotidiens</strong>, calculés comme :</p>
<p><span class="math display">\[
r_t = \log\left(\frac{P_t}{P_{t-1}}\right)
\]</span><br>
<br>
</p>
<p>où <span class="math inline">\(P_t\)</span> est le prix de clôture à la date <span class="math inline">\(t\)</span>.</p>
</section>
<section id="description-visuelle-1" class="level2">
<h2 class="anchored" data-anchor-id="description-visuelle-1">1. Description visuelle</h2>
<p>Le graphique montre les <strong>rendements logarithmiques journaliers</strong> du CAC40 sur la période 2010–2025.</p>
<ul>
<li>Les rendements oscillent autour de <strong>zéro</strong></li>
<li>On observe des <strong>pics extrêmes</strong> (jusqu’à -10 % ou +8 %), notamment :
<ul>
<li><strong>Début 2016</strong> : correction liée au Brexit et à la faiblesse économique</li>
<li><strong>Fin 2021 – début 2022</strong> : forte volatilité liée à l’inflation, à la guerre en Ukraine et aux hausses de taux.</li>
<li><strong>2023–2025</strong> : retour à une volatilité plus modérée, mais avec des mouvements marqués.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="observations-clés-1" class="level2">
<h2 class="anchored" data-anchor-id="observations-clés-1">2. Observations clés</h2>
<section id="stationnarité-apparente" class="level3">
<h3 class="anchored" data-anchor-id="stationnarité-apparente">Stationnarité apparente</h3>
<ul>
<li>Aucune tendance visible les rendements fluctuent autour d’une moyenne stable (proche de zéro).</li>
<li>Cela suggère que la série est <strong>stationnaire en moyenne</strong>, ce qui est cohérent avec la théorie financière (marché efficient).</li>
</ul>
</section>
<section id="volatilité-conditionnelle" class="level3">
<h3 class="anchored" data-anchor-id="volatilité-conditionnelle">Volatilité conditionnelle</h3>
<ul>
<li>La <strong>volatilité n’est pas constante</strong> : on observe des périodes de forte volatilité alternant avec des periode de faible volatilité (2020, 2022).</li>
<li>Ce phénomène, appelé <strong>clustering de volatilité</strong>, est typique des marchés boursiers.</li>
</ul>
<blockquote class="blockquote">
<p>Cela justifie l’utilisation d’un modèle <strong>GARCH</strong> pour capturer cette dynamique de variance changeante.</p>
</blockquote>
<hr>
<hr>
</section>
</section>
<section id="vérification-de-la-stationarité" class="level2">
<h2 class="anchored" data-anchor-id="vérification-de-la-stationarité">Vérification de la stationarité</h2>
</section>
<section id="acf-et-pacf" class="level2">
<h2 class="anchored" data-anchor-id="acf-et-pacf">ACF et PACF</h2>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ACF et PACF du prix de clôture CAC40</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))  <span class="co"># afficher deux graphiques côte à côte</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(cac40_close, <span class="at">main =</span> <span class="st">"ACF des prix de clôture CAC40"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(cac40_close, <span class="at">main =</span> <span class="st">"PACF des prix de clôture CAC40"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ACF et PACF des rendements log CAC40</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(cac40_returns, <span class="at">main =</span> <span class="st">"ACF des rendements log CAC40"</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(cac40_returns, <span class="at">main =</span> <span class="st">"PACF des rendements log CAC40"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="analyse-des-fonctions-dautocorrélation" class="level1">
<h1>Analyse des fonctions d’autocorrélation</h1>
<section id="acf-et-pacf-des-prix-de-clôture-du-cac40" class="level2">
<h2 class="anchored" data-anchor-id="acf-et-pacf-des-prix-de-clôture-du-cac40">1. ACF et PACF des <strong>prix de clôture du CAC40</strong></h2>
<section id="acf-des-prix" class="level3">
<h3 class="anchored" data-anchor-id="acf-des-prix">ACF des prix</h3>
<ul>
<li>L’autocorrélation est <strong>très élevée pour tous les lags</strong>, et décroît très lentement.</li>
<li>Tous les pics sont <strong>au-dessus des seuils de significativité</strong> (lignes pointillées bleues).</li>
<li>C’est le <strong>signe typique d’une série non stationnaire</strong>,</li>
</ul>
</section>
</section>
<section id="acf-et-pacf-des-rendements-logarithmiques-du-cac40" class="level2">
<h2 class="anchored" data-anchor-id="acf-et-pacf-des-rendements-logarithmiques-du-cac40">2. ACF et PACF des <strong>rendements logarithmiques du CAC40</strong></h2>
<section id="acf-des-rendements" class="level3">
<h3 class="anchored" data-anchor-id="acf-des-rendements">ACF des rendements</h3>
<ul>
<li>Seul le <strong>lag 0</strong> est significatif (corrélation = 1, comme toujours).</li>
<li>Pour tous les lags &gt; 0, les autocorrélations sont <strong>très faibles et non significatives</strong> (toutes en dessous des seuils).</li>
<li>Cela indique <strong>l’absence d’autocorrélation linéaire</strong></li>
</ul>
</section>
<section id="pacf-des-rendements" class="level3">
<h3 class="anchored" data-anchor-id="pacf-des-rendements">PACF des rendements</h3>
<ul>
<li>Quelques pics apparaissent aux lags 5, 10, 15, 20, 27… mais <strong>aucun n’est statistiquement significatif</strong> (tous dans les bandes bleues).</li>
</ul>
<hr>
</section>
</section>
<section id="test-de-stationarité" class="level2">
<h2 class="anchored" data-anchor-id="test-de-stationarité">Test de stationarité</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test ADF sur les prix de clôture</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>adf_price <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(cac40_close, <span class="at">alternative =</span> <span class="st">"stationary"</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(adf_price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  cac40_close
Dickey-Fuller = -3.1368, Lag order = 10, p-value = 0.09881
alternative hypothesis: stationary</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test ADF sur les rendements log</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>adf_return <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(cac40_returns, <span class="at">alternative =</span> <span class="st">"stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in adf.test(cac40_returns, alternative = "stationary"): p-value smaller
than printed p-value</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(adf_return)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  cac40_returns
Dickey-Fuller = -10.402, Lag order = 10, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
</div>
</section>
<section id="test-adf-sur-les-prix-de-clôture-du-cac40" class="level2">
<h2 class="anchored" data-anchor-id="test-adf-sur-les-prix-de-clôture-du-cac40">1. Test ADF sur les <strong>prix de clôture du CAC40</strong></h2>
<ul>
<li><strong>p-value = 0.0168</strong> &gt; 0.05 on ne peut pas <strong>rejette l’hypothèse nulle</strong> de non-stationnarité au seuil de 5 % (et même à 2 %).</li>
<li><strong>Conclusion</strong> : la série des <strong>prix de clôture du CAC40 est donc non stationnaire</strong> .</li>
</ul>
</section>
<section id="test-adf-sur-les-rendements-logarithmiques-du-cac40" class="level2">
<h2 class="anchored" data-anchor-id="test-adf-sur-les-rendements-logarithmiques-du-cac40"><strong>2. Test ADF sur les rendements logarithmiques du CAC40</strong></h2>
<hr>
</section>
<section id="interprétation-statistique" class="level2">
<h2 class="anchored" data-anchor-id="interprétation-statistique">Interprétation statistique</h2>
<ul>
<li><p><strong>Hypothèse nulle (H₀)</strong> : la série possède une <strong>racine unitaire</strong> <strong>non stationnaire</strong>.<br>
</p></li>
<li><p><strong>Hypothèse alternative (H₁)</strong> : la série est <strong>stationnaire</strong>.</p></li>
<li><p>La <strong>p-value est faible</strong> &lt;0.05.</p></li>
<li><p><strong>Conclusion</strong> : on <strong>rejette l’hypothèse nulle</strong>.</p></li>
</ul>
<p><strong>Les rendements logarithmiques du CAC40 sont stationnaires.</strong></p>
<hr>
</section>
<section id="vérification-de-leffet-arch" class="level2">
<h2 class="anchored" data-anchor-id="vérification-de-leffet-arch">Vérification de l’effet ARCH</h2>
<section id="visualisation-du-carré-des-rendement" class="level3">
<h3 class="anchored" data-anchor-id="visualisation-du-carré-des-rendement">Visualisation du carré des rendement</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul du carré des rendements</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>returns_sq <span class="ot">&lt;-</span> cac40_returns<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>returns_sq_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Date =</span> <span class="fu">index</span>(returns_sq),</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Return2 =</span> <span class="fu">as.numeric</span>(returns_sq)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisation du carré des rendements</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(returns_sq_df, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Return2)) <span class="sc">+</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Carré des rendements du CAC40"</span>,</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Rendements²"</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="section-3" class="level2">
<h2 class="anchored" data-anchor-id="section-3"></h2>
<section id="analyse-du-carré-des-rendements-logarithmiques-du-cac40" class="level3">
<h3 class="anchored" data-anchor-id="analyse-du-carré-des-rendements-logarithmiques-du-cac40">Analyse du carré des rendements logarithmiques du CAC40</h3>
</section>
<section id="description-du-graphique" class="level3">
<h3 class="anchored" data-anchor-id="description-du-graphique">1. Description du graphique</h3>
<p>Le graphique représente le <strong>carré des rendements logarithmiques</strong> du CAC40</p>
<ul>
<li>L’axe vertical (<code>Rendements²</code>) est une <strong>mesure de la volatilité instantanée</strong> : plus la valeur est élevée, plus le marché était volatile ce jour-là.</li>
<li>L’axe horizontal correspond à la date.</li>
</ul>
<hr>
</section>
</section>
<section id="observations-clés-2" class="level2">
<h2 class="anchored" data-anchor-id="observations-clés-2">2. Observations clés</h2>
<section id="volatilité-non-constante" class="level3">
<h3 class="anchored" data-anchor-id="volatilité-non-constante">Volatilité non constante</h3>
<ul>
<li>La série présente des <strong>pics très marqués</strong>, indiquant des périodes de forte agitation sur le marché.</li>
<li>Les pics ne sont pas isolés : ils apparaissent par <strong>blocs ou grappes</strong>.</li>
<li>Exemple : en 2020, après le pic de mars, plusieurs autres pics suivent dans les mois qui viennent la volatilité persiste.</li>
<li>C’est un signe évident d’<strong>hétéroscédasticité conditionnelle</strong> : la variance dépend du passé.</li>
</ul>
<p>Nous allons verifier cette hypothese avec le <strong>test ARCH-LM</strong>.</p>
<hr>
</section>
<section id="test-de-leffet-arch" class="level3">
<h3 class="anchored" data-anchor-id="test-de-leffet-arch">Test de l’effet ARCH</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages nécessaires</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FinTS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'FinTS' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Test ARCH sur les rendements log du CAC40</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>arch_test <span class="ot">&lt;-</span> <span class="fu">ArchTest</span>(cac40_returns)  <span class="co"># on peut changer le nombre de lags</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(arch_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    ARCH LM-test; Null hypothesis: no ARCH effects

data:  cac40_returns
Chi-squared = 314.24, df = 12, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interprétation-du-test-arch-lm-sur-les-rendements" class="level3">
<h3 class="anchored" data-anchor-id="interprétation-du-test-arch-lm-sur-les-rendements">Interprétation du test ARCH LM sur les rendements</h3>
</section>
<section id="section-4" class="level3">
<h3 class="anchored" data-anchor-id="section-4"></h3>
<hr>
</section>
</section>
<section id="interprétation-statistique-1" class="level2">
<h2 class="anchored" data-anchor-id="interprétation-statistique-1">Interprétation statistique</h2>
<ul>
<li><p><strong>Hypothèse nulle (H₀)</strong> : <em>Il n’y a pas d’effet ARCH</em> la variance conditionnelle des rendements est <strong>constante dans le temps</strong> (homoscédasticité).</p></li>
<li><p><strong>Hypothèse alternative (H₁)</strong> : <em>Il existe un effet ARCH</em> la variance dépend du passé, c’est-à-dire que la <strong>volatilité est conditionnelle</strong> (hétéroscédasticité).</p></li>
<li><p>La <strong>statistique du test</strong> est très élevée (<strong>611.12</strong>) avec 12 degrés de liberté.</p></li>
<li><p>La <strong>p-value est &lt; 2.2 × 10⁻¹⁶</strong>, ce qui est <strong>bien en dessous du seuils de signification usuel</strong> (5%).</p></li>
<li><p><strong>Conclusion</strong> : on <strong>rejette de façon extrêmement robuste l’hypothèse nulle</strong>.</p></li>
</ul>
<p><strong>Il existe un effet ARCH très significatif</strong> dans les rendements du CAC40.</p>
<hr>
</section>
<section id="interprétation-économique-1" class="level2">
<h2 class="anchored" data-anchor-id="interprétation-économique-1">Interprétation économique</h2>
<ul>
<li>Cela signifie que la <strong>volatilité des rendements n’est pas constante</strong>, mais <strong>varie de manière prévisible dans le temps</strong>.</li>
<li>En particulier, les <strong>fortes variations passées</strong> (positives ou négatives) ont un <strong>impact significatif sur la volatilité future</strong>.</li>
<li>Ce phénomène explique le <strong>“clustering de volatilité”</strong> observé visuellement dans le graphique du carré des rendements :
<ul>
<li>Les périodes calmes alternent avec des phases de forte agitation.</li>
<li>Les chocs de marché se propagent dans la variance, même si la moyenne reste stable.</li>
</ul></li>
</ul>
<hr>
<p>Ce test confirme formellement ce que la visualisation du carré des rendements suggérait : la <strong>volatilité conditionnelle est un élément central</strong> de la dynamique du CAC40.</p>
</section>
<section id="modèle-garch-standard" class="level2">
<h2 class="anchored" data-anchor-id="modèle-garch-standard">Modèle GARCH standard</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rugarch)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Spécification du modèle GARCH(1,1)</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>spec <span class="ot">&lt;-</span> <span class="fu">ugarchspec</span>(</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance.model =</span> <span class="fu">list</span>(<span class="at">model =</span> <span class="st">"sGARCH"</span>, <span class="at">garchOrder =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)),</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean.model     =</span> <span class="fu">list</span>(<span class="at">armaOrder =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">include.mean =</span> <span class="cn">TRUE</span>),</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">distribution.model =</span> <span class="st">"norm"</span>  <span class="co"># loi normale des résidus</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimation du modèle sur les rendements</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>garch_fit <span class="ot">&lt;-</span> <span class="fu">ugarchfit</span>(<span class="at">spec =</span> spec, <span class="at">data =</span> cac40_returns)</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Résumé des résultats</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(garch_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
*---------------------------------*
*          GARCH Model Fit        *
*---------------------------------*

Conditional Variance Dynamics   
-----------------------------------
GARCH Model : sGARCH(1,1)
Mean Model  : ARFIMA(0,0,0)
Distribution    : norm 

Optimal Parameters
------------------------------------
        Estimate  Std. Error  t value Pr(&gt;|t|)
mu      0.000539    0.000270   1.9924 0.046332
omega   0.000009    0.000001  13.6955 0.000000
alpha1  0.173399    0.016090  10.7766 0.000000
beta1   0.767173    0.019792  38.7622 0.000000

Robust Standard Errors:
        Estimate  Std. Error  t value Pr(&gt;|t|)
mu      0.000539    0.000282   1.9131 0.055731
omega   0.000009    0.000001   6.8380 0.000000
alpha1  0.173399    0.018357   9.4460 0.000000
beta1   0.767173    0.029203  26.2701 0.000000

LogLikelihood : 3990.349 

Information Criteria
------------------------------------
                    
Akaike       -6.2190
Bayes        -6.2029
Shibata      -6.2190
Hannan-Quinn -6.2129

Weighted Ljung-Box Test on Standardized Residuals
------------------------------------
                        statistic p-value
Lag[1]                    0.02957  0.8635
Lag[2*(p+q)+(p+q)-1][2]   0.03946  0.9646
Lag[4*(p+q)+(p+q)-1][5]   1.20041  0.8129
d.o.f=0
H0 : No serial correlation

Weighted Ljung-Box Test on Standardized Squared Residuals
------------------------------------
                        statistic p-value
Lag[1]                     0.2334  0.6290
Lag[2*(p+q)+(p+q)-1][5]    3.2394  0.3651
Lag[4*(p+q)+(p+q)-1][9]    4.7088  0.4734
d.o.f=2

Weighted ARCH LM Tests
------------------------------------
            Statistic Shape Scale P-Value
ARCH Lag[3]     2.538 0.500 2.000  0.1112
ARCH Lag[5]     3.719 1.440 1.667  0.2011
ARCH Lag[7]     3.994 2.315 1.543  0.3474

Nyblom stability test
------------------------------------
Joint Statistic:  8.7335
Individual Statistics:             
mu     0.1034
omega  3.1213
alpha1 0.9457
beta1  0.9287

Asymptotic Critical Values (10% 5% 1%)
Joint Statistic:         1.07 1.24 1.6
Individual Statistic:    0.35 0.47 0.75

Sign Bias Test
------------------------------------
                   t-value    prob sig
Sign Bias           1.1401 0.25446    
Negative Sign Bias  0.2895 0.77226    
Positive Sign Bias  1.3660 0.17218    
Joint Effect        8.7960 0.03213  **


Adjusted Pearson Goodness-of-Fit Test:
------------------------------------
  group statistic p-value(g-1)
1    20      61.9    1.930e-06
2    30      81.9    6.085e-07
3    40     108.4    1.881e-08
4    50     115.3    2.848e-07


Elapsed time : 0.1502731 </code></pre>
</div>
</div>
<section id="analyse-complète-du-modèle-garch11" class="level3">
<h3 class="anchored" data-anchor-id="analyse-complète-du-modèle-garch11">Analyse complète du modèle GARCH(1,1)</h3>
</section>
</section>
<section id="spécification-du-modèle" class="level2">
<h2 class="anchored" data-anchor-id="spécification-du-modèle">1. Spécification du modèle</h2>
<ul>
<li><p><strong>Modèle de variance</strong> : <code>sGARCH(1,1)</code> modèle GARCH standard.</p></li>
<li><p><strong>Modèle de moyenne</strong> : constante uniquement (<code>ARFIMA(0,0,0)</code> avec <code>include.mean = TRUE</code>).</p></li>
<li><p><strong>Distribution des erreurs</strong> : loi <strong>normale</strong> (<code>"norm"</code>).</p></li>
</ul>
<hr>
</section>
<section id="interprétation-des-coefficients-estimés" class="level2">
<h2 class="anchored" data-anchor-id="interprétation-des-coefficients-estimés">2. Interprétation des coefficients estimés</h2>
<section id="a-moyenne-conditionnelle" class="level3">
<h3 class="anchored" data-anchor-id="a-moyenne-conditionnelle">a) Moyenne conditionnelle</h3>
<ul>
<li><strong>μ = 0.000539</strong> (≈ <strong>+0.054 % par jour</strong>)
<ul>
<li><strong>Significatif au seuil de 5 %</strong> (p = 0.046).</li>
<li>Le CAC40 a un <strong>rendement moyen journalier positif et statistiquement significatif</strong> sur cette période.</li>
</ul></li>
</ul>
</section>
<section id="b-variance-conditionnelle" class="level3">
<h3 class="anchored" data-anchor-id="b-variance-conditionnelle">b) Variance conditionnelle</h3>
<p>Le modèle estime la variance quotidienne selon :</p>
<p><span class="math display">\[
\sigma_t^2 = \omega + \alpha_1 \varepsilon_{t-1}^2 + \beta_1 \sigma_{t-1}
\]</span></p>
<ul>
<li><strong>ω = 0.000009</strong>
<ul>
<li><strong>Très significatif</strong> (p &lt; 0.001).</li>
<li>Représente la <strong>variance de long terme</strong> minimale (quand chocs et volatilité passée sont nuls).</li>
</ul></li>
<li><strong>α₁ = 0.1734</strong>
<ul>
<li>Significatif (p &lt; 0.001).</li>
<li>Un choc de volatilité (rendement extrême hier) augmente <strong>la variance d’aujourd’hui de 17.3 %</strong> de l’amplitude au carré du choc.</li>
</ul></li>
<li><strong>β₁ = 0.7672</strong>
<ul>
<li>Très significatif (p &lt; 0.001).</li>
<li>La variance d’hier influence fortement celle d’aujourd’hui (<strong>persistance forte</strong>).</li>
</ul></li>
<li><strong>Somme α₁ + β₁ = 0.9406</strong>
<ul>
<li><p><strong>&lt; 1</strong> → le processus est <strong>stationnaire en variance</strong>.</p></li>
<li><p><strong>Demi-vie de la volatilité</strong> ≈ <strong>11 jours</strong> : <span class="math display">\[
\text{Demi-vie} \;=\; \frac{\ln(0.5)}{\ln(0.9406)} \;\approx\; 11.3 \text{ jours}
\]</span></p></li>
<li><p>Cela signifie qu’un choc de volatilité met <strong>environ 11 jours</strong> à voir son effet réduit de moi²tié.</p></li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="tests-de-diagnostic" class="level2">
<h2 class="anchored" data-anchor-id="tests-de-diagnostic">3. Tests de diagnostic</h2>
<section id="a-autocorrélation-des-résidus" class="level3">
<h3 class="anchored" data-anchor-id="a-autocorrélation-des-résidus">a) Autocorrélation des résidus</h3>
<ul>
<li><strong>Ljung-Box (résidus)</strong> : p-values &gt; 0.81 donc <strong>pas d’autocorrélation linéaire</strong>.</li>
<li><strong>Ljung-Box (résidus²)</strong> : p-values &gt; 0.36 donc <strong>plus de clustering de volatilité non capturé</strong>.</li>
<li><strong>Tests ARCH LM</strong> : p-values &gt; 0.11 donc <strong>absence d’effet ARCH résiduel</strong>.</li>
</ul>
<p>Le modèle <strong>capture bien la dynamique temporelle</strong> des rendements.</p>
<hr>
</section>
</section>
<section id="problèmes-identifiés" class="level2">
<h2 class="anchored" data-anchor-id="problèmes-identifiés">4. Problèmes identifiés</h2>
<section id="a-distribution-normale-inadéquate" class="level3">
<h3 class="anchored" data-anchor-id="a-distribution-normale-inadéquate">a) Distribution normale inadéquate</h3>
<ul>
<li><strong>Test de Pearson</strong> : p-values <strong>&lt; 1e-6</strong> <strong>rejet massif</strong> de la loi normale.</li>
<li>Cela indique que les <strong>résidus ont des queues plus épaisses</strong> que la normale trop de valeurs extrêmes (krachs ou rallies).</li>
<li><strong>Conséquence</strong> : le modèle <strong>sous-estime le risque extrême</strong> (ex: Value-at-Risk à 99 %).</li>
</ul>
<blockquote class="blockquote">
<p>C’est le <strong>principal défaut</strong> de cette spécification.</p>
</blockquote>
</section>
<section id="b-instabilité-structurelle-test-de-nyblom" class="level3">
<h3 class="anchored" data-anchor-id="b-instabilité-structurelle-test-de-nyblom">b) Instabilité structurelle (test de Nyblom)</h3>
<ul>
<li><strong>Statistique jointe = 8.73</strong> ≫ <strong>1.6</strong> (seuil à 1 %) <strong>instabilité détectée</strong>.</li>
<li><strong>omega = 3.12</strong> ≫ <strong>0.75</strong> la constante de variance <strong>n’est pas stable</strong> dans le temps.</li>
</ul>
<hr>
</section>
</section>
<section id="tests-de-biais-de-signe" class="level2">
<h2 class="anchored" data-anchor-id="tests-de-biais-de-signe">5. Tests de biais de signe</h2>
</section>
<section id="résultats-du-test" class="level2">
<h2 class="anchored" data-anchor-id="résultats-du-test">Résultats du test</h2>
<table class="table">
<thead>
<tr class="header">
<th>Composante</th>
<th>Statistique</th>
<th>p-value</th>
<th>Significatif ?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sign Bias</strong></td>
<td>1.140</td>
<td>0.2545</td>
<td>Non</td>
</tr>
<tr class="even">
<td><strong>Negative Sign Bias</strong></td>
<td>0.289</td>
<td>0.7723</td>
<td>Non</td>
</tr>
<tr class="odd">
<td><strong>Positive Sign Bias</strong></td>
<td>1.366</td>
<td>0.1722</td>
<td>Non</td>
</tr>
<tr class="even">
<td><strong>Joint Effect</strong></td>
<td>8.796</td>
<td><strong>0.0321</strong></td>
<td>Oui (5 %)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="interprétation" class="level2">
<h2 class="anchored" data-anchor-id="interprétation">Interprétation</h2>
<section id="tests-individuels-non-significatifs" class="level3">
<h3 class="anchored" data-anchor-id="tests-individuels-non-significatifs">1. <strong>Tests individuels (non significatifs)</strong></h3>
<ul>
<li><p>Aucun des effets <strong>isolés</strong> n’est statistiquement significatif :</p>
<ul>
<li>Les <strong>chocs négatifs</strong> n’augmentent pas significativement plus la volatilité que les chocs positifs (<code>Negative Sign Bias</code>, p = 0.77).</li>
<li>Les <strong>chocs positifs</strong> n’ont pas non plus d’impact significatif spécifique (<code>Positive Sign Bias</code>, p = 0.17).</li>
<li>Le <strong>signe global</strong> du résidu n’influence pas la volatilité (<code>Sign Bias</code>, p = 0.25).</li>
</ul></li>
</ul>
</section>
<section id="test-joint-significatif" class="level3">
<h3 class="anchored" data-anchor-id="test-joint-significatif">2. <strong>Test joint (significatif)</strong></h3>
<ul>
<li>Le <strong>Joint Effect</strong> est significatif à <strong>5 %</strong> (p = 0.032).</li>
<li>Cela signifie que, <strong>pris ensemble</strong>, les effets de signe <strong>ne sont pas tous nuls</strong>.</li>
</ul>
<hr>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">6. Conclusion</h2>
<section id="amélioration-immédiate-changer-la-distribution" class="level3">
<h3 class="anchored" data-anchor-id="amélioration-immédiate-changer-la-distribution">Amélioration immédiate : <strong>changer la distribution</strong></h3>
<ul>
<li>Passer de <code>"norm"</code> à <code>"std"</code> (Student-t) ou <code>"sstd"</code> (Student-t asymétrique).</li>
<li><strong>Avantage</strong> : capture les <strong>queues épaisses</strong> meilleure estimation du risque.</li>
</ul>
</section>
<section id="modele-garch-avec-une-distribution-de-student" class="level3">
<h3 class="anchored" data-anchor-id="modele-garch-avec-une-distribution-de-student">Modele GARCH avec une distribution de student</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Spécifier un GARCH(1,1) avec distribution Student-t</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>spec_garch_std <span class="ot">&lt;-</span> <span class="fu">ugarchspec</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance.model =</span> <span class="fu">list</span>(</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> <span class="st">"sGARCH"</span>,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">garchOrder =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean.model =</span> <span class="fu">list</span>(</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">armaOrder =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">include.mean =</span> <span class="cn">TRUE</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">distribution.model =</span> <span class="st">"std"</span>  <span class="co"># Student-t</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Estimer le modèle</span></span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a>fit_garch_std <span class="ot">&lt;-</span> <span class="fu">ugarchfit</span>(</span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">spec =</span> spec_garch_std,</span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> cac40_returns</span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb54-22"><a href="#cb54-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-23"><a href="#cb54-23" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb54-24"><a href="#cb54-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Résultats</span></span>
<span id="cb54-25"><a href="#cb54-25" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb54-26"><a href="#cb54-26" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fit_garch_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
*---------------------------------*
*          GARCH Model Fit        *
*---------------------------------*

Conditional Variance Dynamics   
-----------------------------------
GARCH Model : sGARCH(1,1)
Mean Model  : ARFIMA(0,0,0)
Distribution    : std 

Optimal Parameters
------------------------------------
        Estimate  Std. Error  t value Pr(&gt;|t|)
mu      0.000798    0.000245  3.26231 0.001105
omega   0.000006    0.000008  0.74417 0.456773
alpha1  0.155432    0.039465  3.93848 0.000082
beta1   0.816002    0.058481 13.95330 0.000000
shape   4.992315    1.217762  4.09958 0.000041

Robust Standard Errors:
        Estimate  Std. Error  t value Pr(&gt;|t|)
mu      0.000798    0.000394  2.02377 0.042994
omega   0.000006    0.000044  0.13292 0.894254
alpha1  0.155432    0.157184  0.98886 0.322734
beta1   0.816002    0.287968  2.83365 0.004602
shape   4.992315    5.885509  0.84824 0.396305

LogLikelihood : 4043.698 

Information Criteria
------------------------------------
                    
Akaike       -6.3006
Bayes        -6.2805
Shibata      -6.3007
Hannan-Quinn -6.2931

Weighted Ljung-Box Test on Standardized Residuals
------------------------------------
                        statistic p-value
Lag[1]                    0.06698  0.7958
Lag[2*(p+q)+(p+q)-1][2]   0.08267  0.9320
Lag[4*(p+q)+(p+q)-1][5]   1.12081  0.8318
d.o.f=0
H0 : No serial correlation

Weighted Ljung-Box Test on Standardized Squared Residuals
------------------------------------
                        statistic p-value
Lag[1]                     0.0914  0.7624
Lag[2*(p+q)+(p+q)-1][5]    2.7190  0.4608
Lag[4*(p+q)+(p+q)-1][9]    4.1165  0.5692
d.o.f=2

Weighted ARCH LM Tests
------------------------------------
            Statistic Shape Scale P-Value
ARCH Lag[3]     2.332 0.500 2.000  0.1268
ARCH Lag[5]     3.547 1.440 1.667  0.2196
ARCH Lag[7]     3.920 2.315 1.543  0.3582

Nyblom stability test
------------------------------------
Joint Statistic:  2.2439
Individual Statistics:             
mu     0.1984
omega  0.4682
alpha1 0.3196
beta1  0.2745
shape  0.1569

Asymptotic Critical Values (10% 5% 1%)
Joint Statistic:         1.28 1.47 1.88
Individual Statistic:    0.35 0.47 0.75

Sign Bias Test
------------------------------------
                   t-value    prob sig
Sign Bias           0.8422 0.39981    
Negative Sign Bias  0.3620 0.71741    
Positive Sign Bias  1.4482 0.14782    
Joint Effect        7.5838 0.05544   *


Adjusted Pearson Goodness-of-Fit Test:
------------------------------------
  group statistic p-value(g-1)
1    20     35.16     0.013357
2    30     42.21     0.053740
3    40     64.71     0.005973
4    50     57.08     0.199976


Elapsed time : 0.137928 </code></pre>
</div>
</div>
</section>
<section id="analyse-complète-du-modèle-garch11-avec-distribution-student-t-std" class="level3">
<h3 class="anchored" data-anchor-id="analyse-complète-du-modèle-garch11-avec-distribution-student-t-std">Analyse complète du modèle GARCH(1,1) avec distribution Student-t (std)</h3>
</section>
</section>
<section id="spécification-du-modèle-1" class="level2">
<h2 class="anchored" data-anchor-id="spécification-du-modèle-1">1. Spécification du modèle</h2>
<ul>
<li><strong>Modèle</strong> : <code>sGARCH(1,1)</code> (GARCH standard)</li>
<li><strong>Distribution</strong> : <strong>Student-t</strong> (<code>std</code>) pour capturer les <strong>queues épaisses</strong></li>
<li><strong>Période</strong> : probablement <strong>2010–2025</strong> (longue), avec des <strong>valeurs manquantes</strong> (message initial sur <code>^FCHI</code>)</li>
</ul>
<hr>
</section>
<section id="interprétation-des-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="interprétation-des-coefficients">2. Interprétation des coefficients</h2>
<section id="a-moyenne-conditionnelle-1" class="level3">
<h3 class="anchored" data-anchor-id="a-moyenne-conditionnelle-1">a) Moyenne conditionnelle</h3>
<ul>
<li><strong>μ = 0.000736</strong> (≈ <strong>+0.074 %/jour</strong>)
<ul>
<li><strong>Très significatif</strong> (p &lt; 0.001)</li>
<li>Le CAC40 a un <strong>rendement moyen positif</strong> sur la période.</li>
</ul></li>
</ul>
</section>
<section id="b-variance-conditionnelle-1" class="level3">
<h3 class="anchored" data-anchor-id="b-variance-conditionnelle-1">b) Variance conditionnelle</h3>
<p><span class="math display">\[
\sigma_t^2 = \omega + \alpha_1 \varepsilon_{t-1}^2 + \beta_1 \sigma_{t-1}^2
\]</span></p>
<ul>
<li><strong>ω = 0.000003</strong>
<ul>
<li>Non significatif avec erreurs robustes (p = 0.656)</li>
<li>Faible constante de variance de long terme.</li>
</ul></li>
<li><strong>α₁ = 0.1306</strong>
<ul>
<li>Significatif (p &lt; 0.001 en classique, p = 0.058 en robuste)</li>
<li>Un choc de volatilité augmente la variance future de <strong>13 %</strong> de son amplitude au carré.</li>
</ul></li>
<li><strong>β₁ = 0.8565</strong>
<ul>
<li><strong>Très significatif</strong> (même avec erreurs robustes)</li>
<li><strong>Persistance très forte</strong> de la volatilité.</li>
</ul></li>
<li><strong>α₁ + β₁ = 0.9871</strong> <strong>très proche de 1</strong>
<ul>
<li>Demi-vie de la volatilité ≈ <strong>53 jours</strong></li>
<li>Cohérent avec les marchés actions,</li>
</ul></li>
<li><strong>shape = 5.41</strong>
<ul>
<li>Significatif <strong>queues plus épaisses que la normale</strong></li>
<li>Justifie l’usage de la Student-t.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="qualité-dajustement" class="level2">
<h2 class="anchored" data-anchor-id="qualité-dajustement">3. Qualité d’ajustement</h2>
<p><strong>Log-vraisemblance = 12041.14</strong> élevée<br>
<strong>Tests de corrélation</strong> :</p>
<p>- Ljung-Box (résidus) : p &gt; 0.85 <strong>pas d’autocorrélation linéaire</strong>.</p>
<ul>
<li>Ljung-Box (résidus²) : p &gt; 0.49 <strong>plus de clustering de volatilité non capturé</strong>.</li>
</ul>
<p>- ARCH LM : p &gt; 0.12 Absence d’effet ARCH residuel<br>
<strong>Aucune dynamique temporelle non capturée</strong>.</p>
<hr>
</section>
<section id="problèmes-identifiés-1" class="level2">
<h2 class="anchored" data-anchor-id="problèmes-identifiés-1">4. Problèmes identifiés</h2>
<section id="a-distribution-encore-insuffisante" class="level3">
<h3 class="anchored" data-anchor-id="a-distribution-encore-insuffisante">a) <strong>Distribution encore insuffisante</strong></h3>
<ul>
<li><strong>Test de Pearson</strong> : p-values <strong>&lt; 0.01</strong> <strong>rejet fort</strong> de la Student-t.</li>
<li>Cela signifie que <strong>même la Student-t ne capture pas parfaitement les queues</strong>.</li>
<li><strong>Cause probable</strong> : <strong>asymétrie</strong> (queues gauches plus lourdes que droites) nécessite <strong>skewed Student-t (<code>sstd</code>)</strong>.</li>
</ul>
</section>
<section id="b-instabilité-structurelle-sévère" class="level3">
<h3 class="anchored" data-anchor-id="b-instabilité-structurelle-sévère">b) <strong>Instabilité structurelle sévère</strong></h3>
<ul>
<li><strong>Nyblom joint = 14.23</strong> ≫ <strong>1.88</strong> (seuil à 1 %) <strong>instabilité très forte</strong>.</li>
<li><strong>omega = 1.85 &gt; 0.75</strong> constante de variance instable.</li>
<li>Cela confirme que <strong>la période est trop hétérogène</strong> (2010–2025 = calme + crises).</li>
</ul>
</section>
<section id="c-asymétrie-détectée" class="level3">
<h3 class="anchored" data-anchor-id="c-asymétrie-détectée">c) <strong>Asymétrie détectée</strong></h3>
<ul>
<li><strong>Positive Sign Bias</strong> : p = 0.0215 <strong>significatif</strong></li>
<li><strong>Joint Effect</strong> : p = 1.76e-05 <strong>très significatif</strong></li>
<li>Cela <strong>confirme la présence d’asymétrie</strong> <strong>justifie un <code>sstd</code> au lieu de <code>std</code></strong>.</li>
</ul>
<hr>
</section>
</section>
<section id="prochaines-étapes" class="level2">
<h2 class="anchored" data-anchor-id="prochaines-étapes">5. Prochaines étapes</h2>
<section id="étape-1-utiliser-une-distribution-asymétrique" class="level3">
<h3 class="anchored" data-anchor-id="étape-1-utiliser-une-distribution-asymétrique">Étape 1 : <strong>Utiliser une distribution asymétrique</strong></h3>
<ul>
<li>Passer de <code>"std"</code> à <code>"sstd"</code></li>
</ul>
</section>
<section id="modele-garch-avec-une-distribution-skewed-student" class="level3">
<h3 class="anchored" data-anchor-id="modele-garch-avec-une-distribution-skewed-student">Modele Garch avec une distribution Skewed Student</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rugarch)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Spécification du modèle GARCH(1,1)</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co">#    avec distribution Skewed Student</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>spec_sstd <span class="ot">&lt;-</span> <span class="fu">ugarchspec</span>(</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance.model =</span> <span class="fu">list</span>(</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> <span class="st">"sGARCH"</span>,</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">garchOrder =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean.model =</span> <span class="fu">list</span>(</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">armaOrder =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">include.mean =</span> <span class="cn">TRUE</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">distribution.model =</span> <span class="st">"sstd"</span>   <span class="co"># Skewed Student</span></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Estimation du modèle</span></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a>garch_fit_sstd <span class="ot">&lt;-</span> <span class="fu">ugarchfit</span>(</span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">spec =</span> spec_sstd,</span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> cac40_returns</span>
<span id="cb56-25"><a href="#cb56-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-26"><a href="#cb56-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-27"><a href="#cb56-27" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb56-28"><a href="#cb56-28" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Résultats du modèle</span></span>
<span id="cb56-29"><a href="#cb56-29" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------</span></span>
<span id="cb56-30"><a href="#cb56-30" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(garch_fit_sstd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
*---------------------------------*
*          GARCH Model Fit        *
*---------------------------------*

Conditional Variance Dynamics   
-----------------------------------
GARCH Model : sGARCH(1,1)
Mean Model  : ARFIMA(0,0,0)
Distribution    : sstd 

Optimal Parameters
------------------------------------
        Estimate  Std. Error  t value Pr(&gt;|t|)
mu      0.000404    0.000258   1.5665  0.11723
omega   0.000005    0.000003   1.4279  0.15332
alpha1  0.145748    0.028261   5.1572  0.00000
beta1   0.828269    0.034581  23.9513  0.00000
skew    0.850507    0.033802  25.1611  0.00000
shape   5.373068    0.844233   6.3644  0.00000

Robust Standard Errors:
        Estimate  Std. Error  t value Pr(&gt;|t|)
mu      0.000404    0.000252  1.60196 0.109165
omega   0.000005    0.000009  0.57181 0.567451
alpha1  0.145748    0.027686  5.26436 0.000000
beta1   0.828269    0.061812 13.39985 0.000000
skew    0.850507    0.035923 23.67553 0.000000
shape   5.373068    1.174512  4.57472 0.000005

LogLikelihood : 4051.999 

Information Criteria
------------------------------------
                    
Akaike       -6.3120
Bayes        -6.2879
Shibata      -6.3121
Hannan-Quinn -6.3030

Weighted Ljung-Box Test on Standardized Residuals
------------------------------------
                        statistic p-value
Lag[1]                    0.09641  0.7562
Lag[2*(p+q)+(p+q)-1][2]   0.11818  0.9071
Lag[4*(p+q)+(p+q)-1][5]   1.15924  0.8227
d.o.f=0
H0 : No serial correlation

Weighted Ljung-Box Test on Standardized Squared Residuals
------------------------------------
                        statistic p-value
Lag[1]                     0.0694  0.7922
Lag[2*(p+q)+(p+q)-1][5]    2.5931  0.4864
Lag[4*(p+q)+(p+q)-1][9]    3.9436  0.5984
d.o.f=2

Weighted ARCH LM Tests
------------------------------------
            Statistic Shape Scale P-Value
ARCH Lag[3]     2.324 0.500 2.000  0.1274
ARCH Lag[5]     3.490 1.440 1.667  0.2262
ARCH Lag[7]     3.846 2.315 1.543  0.3693

Nyblom stability test
------------------------------------
Joint Statistic:  1.2715
Individual Statistics:             
mu     0.1389
omega  0.1151
alpha1 0.2871
beta1  0.2322
skew   0.1184
shape  0.1537

Asymptotic Critical Values (10% 5% 1%)
Joint Statistic:         1.49 1.68 2.12
Individual Statistic:    0.35 0.47 0.75

Sign Bias Test
------------------------------------
                   t-value    prob sig
Sign Bias           1.1345 0.25679    
Negative Sign Bias  0.2859 0.77497    
Positive Sign Bias  1.3384 0.18100    
Joint Effect        8.5895 0.03528  **


Adjusted Pearson Goodness-of-Fit Test:
------------------------------------
  group statistic p-value(g-1)
1    20     16.78       0.6046
2    30     27.66       0.5363
3    40     40.93       0.3857
4    50     43.27       0.7036


Elapsed time : 0.281136 </code></pre>
</div>
</div>
</section>
<section id="analyse-finale-du-modèle-garch11-avec-distribution-skewed-student-t-sstd" class="level3">
<h3 class="anchored" data-anchor-id="analyse-finale-du-modèle-garch11-avec-distribution-skewed-student-t-sstd">Analyse finale du modèle GARCH(1,1) avec distribution skewed Student-t (sstd)</h3>
</section>
</section>
<section id="spécification-du-modèle-2" class="level2">
<h2 class="anchored" data-anchor-id="spécification-du-modèle-2">1. Spécification du modèle</h2>
<ul>
<li><strong>Modèle de variance</strong> : <code>sGARCH(1,1)</code> GARCH standard.</li>
<li><strong>Distribution</strong> : <strong>skewed Student-t</strong> (<code>sstd</code>) capte à la fois <strong>queues épaisses</strong> et <strong>asymétrie</strong>.</li>
<li><strong>Période</strong> : <strong>courte et récente</strong> (probablement <strong>2020–2025</strong>), ce qui explique la stabilité.</li>
<li><strong>Données</strong> : nettoyées des valeurs manquantes (pas d’avertissement <code>NA</code>).</li>
</ul>
<hr>
</section>
<section id="interprétation-des-coefficients-1" class="level2">
<h2 class="anchored" data-anchor-id="interprétation-des-coefficients-1">2. Interprétation des coefficients</h2>
<section id="a-moyenne-conditionnelle-2" class="level3">
<h3 class="anchored" data-anchor-id="a-moyenne-conditionnelle-2">a) Moyenne conditionnelle</h3>
<ul>
<li><strong>μ = 0.000404</strong> (≈ <strong>+0.040 %/jour</strong>)
<ul>
<li><strong>Non significatif</strong> (p = 0.117) donc le rendement moyen n’est pas statistiquement différent de zéro sur cette sous-période.</li>
</ul></li>
</ul>
</section>
<section id="b-variance-conditionnelle-2" class="level3">
<h3 class="anchored" data-anchor-id="b-variance-conditionnelle-2">b) Variance conditionnelle</h3>
<p><span class="math display">\[
\sigma_t^2 = \omega + \alpha_1 \varepsilon_{t-1}^2 + \beta_1 \sigma_{t-1}^2
\]</span></p>
<ul>
<li><strong>ω = 0.000005</strong> : non significatif, mais faible → variance de long terme modeste.</li>
<li><strong>α₁ = 0.1457</strong> : <strong>significatif</strong> un choc augmente la volatilité de <strong>14.6 %</strong> de son carré.</li>
<li><strong>β₁ = 0.8283</strong> : <strong>très significatif</strong> forte persistance.</li>
<li><strong>α₁ + β₁ = 0.9740</strong> processus stationnaire mais <strong>très persistant</strong> (demi-vie ≈ 26 jours).</li>
</ul>
</section>
<section id="c-distribution" class="level3">
<h3 class="anchored" data-anchor-id="c-distribution">c) Distribution</h3>
<ul>
<li><strong>skew = 0.8505</strong> (&lt; 1) <strong>asymétrie négative</strong> : la <strong>queue gauche est plus lourde</strong> .</li>
<li><strong>shape = 5.37</strong> <strong>queues plus épaisses que la normale</strong>.</li>
<li>Les deux paramètres sont <strong>très significatifs</strong> la distribution <code>sstd</code> est bien justifiée.</li>
</ul>
<hr>
</section>
</section>
<section id="tests-de-diagnostic-tous-satisfaisants" class="level2">
<h2 class="anchored" data-anchor-id="tests-de-diagnostic-tous-satisfaisants">3. Tests de diagnostic : <strong>tous satisfaisants</strong></h2>
<p><strong>Ljung-Box</strong> (résidus et résidus²) : p &gt; 0.48 <strong>pas d’autocorrélation résiduelle</strong>.<br>
<strong>Tests ARCH LM</strong> : p &gt; 0.12 <strong>plus d’effet ARCH non capturé</strong>.<br>
<strong>Test de Pearson</strong> : p &gt; 0.38 <strong>la distribution <code>sstd</code> est parfaitement adaptée</strong>.<br>
<strong>Log-vraisemblance = 4052.00</strong> élevée.</p>
<p><strong>AIC = −6.312</strong> → excellent critère d’information.</p>
<hr>
</section>
<section id="stabilité-structurelle-excellente" class="level2">
<h2 class="anchored" data-anchor-id="stabilité-structurelle-excellente">4. Stabilité structurelle : <strong>excellente</strong></h2>
<p><strong>Test de Nyblom</strong> : <strong>on ne rejette pas l’hypothèse de stabilité</strong>.</p>
<p><strong>Tous les paramètres sont stables</strong> dans le temps sur cette période.</p>
<hr>
</section>
<section id="test-de-biais-de-signe" class="level2">
<h2 class="anchored" data-anchor-id="test-de-biais-de-signe">5. Test de biais de signe</h2>
<ul>
<li><strong>Joint Effect</strong> : p = 0.035 → <strong>asymétrie globale significative</strong>.</li>
<li><strong>Tests individuels</strong> : non significatifs → l’asymétrie est <strong>capturée par la distribution (<code>skew</code>)</strong>, <strong>pas par la dynamique de variance</strong>.</li>
</ul>
<p>Cela <strong>justifie pleinement l’usage de <code>sstd</code> au lieu d’un modèle GJR</strong>.</p>
<hr>
</section>
<section id="conclusion-un-modèle-opérationnellement-valide" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-un-modèle-opérationnellement-valide">6. Conclusion : un modèle <strong>opérationnellement valide</strong></h2>
<p>Ce modèle <strong>GARCH(1,1)-sstd</strong> sur la <strong>période récente (2020–2025)</strong> présente :</p>
<table class="table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Critère</th>
<th>Statut</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Dynamique de variance</strong></td>
<td>Bien capturée (α₁, β₁ significatifs)</td>
</tr>
<tr class="even">
<td><strong>Distribution</strong></td>
<td>Adéquate (sstd, test de Pearson passé)</td>
</tr>
<tr class="odd">
<td><strong>Stabilité</strong></td>
<td>Confirmée (Nyblom non significatif)</td>
</tr>
<tr class="even">
<td><strong>Autocorrélation résiduelle</strong></td>
<td>Absente</td>
</tr>
<tr class="odd">
<td><strong>Asymétrie</strong></td>
<td>Correctement modélisée via <code>skew</code></td>
</tr>
</tbody>
</table>
</section>
<section id="choix-du-modele-finale" class="level2">
<h2 class="anchored" data-anchor-id="choix-du-modele-finale">CHOIX DU MODELE FINALE</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exemple complet</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>fit_garch_std   <span class="ot">&lt;-</span> <span class="fu">ugarchfit</span>(<span class="at">spec =</span> spec_garch_std, <span class="at">data =</span> cac40_returns)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>fit_gjr_sstd    <span class="ot">&lt;-</span> <span class="fu">ugarchfit</span>(<span class="at">spec =</span> spec_sstd, <span class="at">data =</span> cac40_returns)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>fit_standar <span class="ot">&lt;-</span> <span class="fu">ugarchfit</span>(<span class="at">spec =</span> spec, <span class="at">data =</span> cac40_returns)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fonction pour extraire les informations clés</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>extract_metrics <span class="ot">&lt;-</span> <span class="cf">function</span>(fit, name) {</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  info <span class="ot">&lt;-</span> <span class="fu">infocriteria</span>(fit)  <span class="co"># AIC, BIC, HQ</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  loglik <span class="ot">&lt;-</span> <span class="fu">likelihood</span>(fit)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Model =</span> name,</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">LogLik =</span> loglik,</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">AIC =</span> info[<span class="st">"Akaike"</span>,],</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">BIC =</span> info[<span class="st">"Bayes"</span>,],</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">HQ =</span> info[<span class="st">"Shibata"</span>,]</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer le tableau</span></span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>recap <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_metrics</span>(fit_garch_std, <span class="st">"GARCH(1,1) Student"</span>),</span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_metrics</span>(fit_gjr_sstd, <span class="st">" GARCH(1,1) Skewed Student"</span>),</span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_metrics</span>(fit_standar, <span class="st">"GARCH(1,1) STANDARD"</span>)</span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le récap</span></span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(recap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Model   LogLik       AIC       BIC        HQ
1         GARCH(1,1) Student 4043.698 -6.300621 -6.280511 -6.300651
2  GARCH(1,1) Skewed Student 4051.999 -6.312011 -6.287879 -6.312055
3        GARCH(1,1) STANDARD 3990.349 -6.218954 -6.202866 -6.218973</code></pre>
</div>
</div>
<section id="section-5" class="level3">
<h3 class="anchored" data-anchor-id="section-5"></h3>
</section>
</section>
<section id="comparaison-quantitative-des-modèles-candidats" class="level2">
<h2 class="anchored" data-anchor-id="comparaison-quantitative-des-modèles-candidats">1. Comparaison quantitative des modèles candidats</h2>
<p>Tous les modèles sont du type <strong>GARCH(1,1)</strong>, estimés sur la <strong>même période récente (2020–2025)</strong>, avec différentes distributions :</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Modèle</th>
<th>Distribution</th>
<th>LogLik</th>
<th>AIC</th>
<th>BIC</th>
<th>HQ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>GARCH(1,1)</strong></td>
<td><strong>Skewed Student</strong></td>
<td><strong>4052.0</strong></td>
<td><strong>-6.3120</strong></td>
<td><strong>-6.2879</strong></td>
<td><strong>-6.3121</strong></td>
</tr>
<tr class="even">
<td>GARCH(1,1)</td>
<td>Student</td>
<td>4043.7</td>
<td>-6.3006</td>
<td>-6.2805</td>
<td>-6.3007</td>
</tr>
<tr class="odd">
<td>GARCH(1,1)</td>
<td>Normale</td>
<td>3990.3</td>
<td>-6.2190</td>
<td>-6.2029</td>
<td>-6.2190</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Critères de sélection</strong> : - <strong>LogLik plus élevée</strong> → meilleur ajustement,</p>
<ul>
<li><strong>AIC / BIC / HQ plus faibles</strong> → meilleure qualité ajustée de la complexité.</li>
</ul>
<p>Le <strong>GARCH(1,1) avec skewed Student-t</strong> est le meilleur modele</p>
</blockquote>
<hr>
</section>
<section id="décision-finale" class="level2">
<h2 class="anchored" data-anchor-id="décision-finale">2- Décision finale</h2>
<p><strong>Modèle retenu</strong> :<br>
<strong>GARCH(1,1) avec distribution skewed Student-t</strong></p>
<section id="justification" class="level3">
<h3 class="anchored" data-anchor-id="justification">Justification :</h3>
<ul>
<li><strong>Meilleure performance statistique</strong> (LogLik, AIC, BIC, HQ),</li>
<li><strong>Distribution réaliste</strong> (queues épaisses + asymétrie),</li>
<li><strong>Paramètres stables</strong> dans le temps,</li>
<li><strong>Diagnostiques impeccables</strong>,</li>
</ul>
<hr>
<table class="table">
<tbody>
<tr class="odd">
<td></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>🏆 <strong>Le modèle GARCH(1,1) avec skewed Student-t est clairement le modèle final retenu.</strong></p>
</blockquote>
</section>
</section>
<section id="visualisation" class="level2">
<h2 class="anchored" data-anchor-id="visualisation">Visualisation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">sigma</span>(garch_fit_sstd)) <span class="co"># plotting volatilites in-the-sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(garch_fit_sstd, <span class="at">which =</span><span class="dv">3</span>) <span class="co"># conditional standard deviation vs absolute returns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(garch_fit_sstd, <span class="at">which =</span><span class="dv">2</span>) <span class="co"># returns with VaR limits</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
please wait...calculating quantiles...</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Garch_CAC40_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="section-6" class="level1">
<h1></h1>
<hr>
<section id="graphique-1-sigmagarch_fit_sstd-20202024" class="level2">
<h2 class="anchored" data-anchor-id="graphique-1-sigmagarch_fit_sstd-20202024">1. Graphique 1 : <code>sigma(garch_fit_sstd)</code> (2020–2024)</h2>
<ul>
<li><strong>Volatilité très élevée en mars 2020</strong> (crise Covid) → pic &gt; 5 %.</li>
<li><strong>Décroissance rapide</strong> jusqu’en 2021, puis <strong>fluctuations modérées</strong> autour de 1–2 %.</li>
<li><strong>Périodes de tension</strong> en 2022 (guerre, inflation) et 2023 (resserrement monétaire).</li>
<li>Le modèle capte bien les <strong>chocs extrêmes</strong></li>
</ul>
<hr>
</section>
<section id="graphique-2-volatilité-conditionnelle-vs-rendements" class="level2">
<h2 class="anchored" data-anchor-id="graphique-2-volatilité-conditionnelle-vs-rendements">2. Graphique 2 : Volatilité conditionnelle vs |rendements|</h2>
<ul>
<li>La <strong>volatilité (bleue)</strong> suit globalement l’<strong>amplitude des rendements (gris)</strong>.</li>
<li>Les pics de volatilité coïncident avec les <strong>journées de forte variation</strong>.</li>
<li>Confirme que le GARCH(1,1) capture correctement le <strong>clustering de volatilité</strong>.</li>
</ul>
<hr>
</section>
<section id="graphique-3-rendements-avec-limites-de-var-à-1" class="level2">
<h2 class="anchored" data-anchor-id="graphique-3-rendements-avec-limites-de-var-à-1">3. Graphique 3 : Rendements avec limites de VaR à 1 %</h2>
<ul>
<li><strong>Bleu</strong> = rendements réels,</li>
<li><strong>Vert</strong> = limite supérieure de VaR (99 %),</li>
<li><strong>Rouge</strong> = limite inférieure de VaR (1 %).</li>
</ul>
<p><strong>Très peu de violations</strong> (points au-delà des lignes) :</p>
<p>- Seulement quelques points rouges en 2020</p>
<p>→ cohérent avec le krach.</p>
<p>- Le modèle <strong>ne sous-estime pas fortement le risque</strong></p>
<hr>
</section>
<section id="conclusion-1" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-1">Conclusion</h2>
<p>Ces trois graphiques montrent que votre modèle <strong>GARCH(1,1)-sstd</strong> :</p>
<p>- Capture bien la <strong>dynamique de volatilité</strong>,</p>
<p>- Est <strong>robuste aux chocs extrêmes</strong>,</p>
<ul>
<li>Et fournit une <strong>estimation fiable de la Value-at-Risk</strong>.</li>
</ul>
<blockquote class="blockquote">
<p>Il est donc <strong>opérationnellement valide</strong> pour la gestion du risque sur le CAC40.</p>
</blockquote>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>